### ISSUE TITLE
Covers being overridden.

### ISSUE THREAD

**Issue by craigjohnwright** [dtinth/babel-plugin-__coverage__#8]
I have a case where I am testing two classes, A and B for brevity, where B is a subclass of A. There are two test files, one for each class, TestA and TestB.

When SpecA is _webpacked_ it contains class A with covers. When TestB is _webpacked_ it contains class A and B, each with covers. The covers are correctly recorded when TestA is run. When TestB is run the covers recorded for class A are overridden by the `coverageTemplate` method `GET_INITIAL_FILE_COVERAGE()`.

This is a direct result of commit 5a75bc1f11287304a2650c50f5c9d4aab4864ee8. Reverting this change fixes the issue.

**Comment by dtinth** [comment]
Thanks for your report!

I see, so this is a result of each test being webpacked separately, which leads to a module’s initialization code executing twice rather than once.

Actually, I made it work like this in order to address another use case, where Mocha is run on watch mode. When a file is changed, it re-compiles and executes the code under the same global context. In this case, there will be a mismatch in the number of branches between old code and new code, that’s why I modified this plugin to overwrite the coverage data.

This is the only change in v0.11111.0 and v0.111111.0, so please stick with v0.11111.0 for now.

To fix this, I’m thinking about creating a checksum for initial coverage data and only overwrite the data in the case of checksum mismatch. This is so that it can handle both your use case and my use case without requiring configuration.

**Comment by dtinth** [comment]
Pushed as v0.111111.1.
