### ISSUE TITLE
v0.111111.0 not measuring branches correctly?

### ISSUE THREAD

**Issue by JaKXz** [dtinth/babel-plugin-__coverage__#9]
Looking at https://github.com/rangle/react-redux-starter/pull/124, the previous version measured 42 branches (checkout master), and the latest version measures only 2 branches.

**Comment by JaKXz** [comment]
cc @kentcdodds is there a default for ignoring files? I fear what's happening here is that only one of my files here is being instrumented against when I don't specify `only` or `ignore` in my `.babelrc`.

**Comment by kentcdodds** [comment]
Try specifying a bogus ignore to see if that makes a difference...

**Comment by JaKXz** [comment]
That did it. Thanks!

**Comment by JaKXz** [comment]
Though, @dtinth, as you might have seen in our repo, we use nyc's `exclude` option. In another project, I use nyc's `include` option, and they both work just fine...

**Comment by dtinth** [comment]
@JaKXz I’m sorry, but I don’t quite get what you mean by using nyc’s `exclude`/`include` option, because that has nothing to do with the coverage plugin. 😕

Please note that `nyc` uses Istanbul to instrument the source file under-the-hood. Therefore if nyc isn’t properly configured to not instrument files, then the file will be instrumented twice and can impact code coverage result. 💣

That’s why I recommend setting `"include"` to a non-existent path. If that results in coverage failing to be measured, then Babel has not been configured properly. ;)
